apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

repositories {
    mavenLocal()
    google()
    mavenCentral()
}

android {
    namespace 'com.mgl.fleet.flutter'
    compileSdkVersion 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    defaultConfig {
        minSdkVersion 24
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
}

dependencies {
        implementation 'com.mgl.sdk:fleet-android:0.2.0'
}
